version: '3.3'

services:
  db:
    image: postgres:10
    volumes:
      - sck-postgres:/var/lib/postgresql/data

  redis:
    image: redis:4

  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - mqtt
    volumes:
      - "./:/app"
    command: rails server -p 3000 -b '0.0.0.0'

  sidekiq:
    build: .
    env_file: .env
    depends_on:
      - app
      - redis
    command: bundle exec sidekiq

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
#    volumes:
#      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"

volumes:
  sck-postgres:
