version: '2.2'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - sck-postgres:/var/lib/postgresql/data

  redis:
    image: redis

  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - "./:/app"
    command: rails server -p 3000 -b '0.0.0.0'

  sidekiq:
    build: .
    env_file: .env
    depends_on:
      - app
      - redis
    command: bundle exec sidekiq

#TODO: Work in progress
# There is no official docker image for Kairos 2017-12-18
#  kairos:
#    image: kairos
#    ports:
#      - "8080:8080"
#      - "4242:4242"

  cassandra:
    image: cassandra
    ports:
      # no need to expose all ports?
      - "7000:7000" # Internode, cluster communication
      - "7001:7001" # TLS Internode
      - "7199:7199" # JMX
      - "9042:9042" # CQL native transport
      - "9160:9160" # Thrift client API

volumes:
  sck-postgres:
