version: '2.2'

services:
  db:
    image: postgres:9.4.5
    ports:
      - '5432:5432'
    volumes:
      - sck-postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest

  app:
    build: .
    ports:
      - "3000:3000"
    command: rails server
    depends_on:
      - db
      - redis
    volumes:
      - "./:/app"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - app
      - redis
    env_file: .env

volumes:
  sck-postgres:
