version: '2.2'

services:
  db:
    image: postgres:9.4.5
    ports:
      - '5432:5432'
    volumes:
      - sck-postgres:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    command: rails server

  redis:
    image: redis:3.2

  sidekiq:
    build: .
    command: bundle exec sidekiq


volumes:
  sck-postgres:
